apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      color: green
  template:
    metadata:
      labels:
        app: myapp
        color: green
    spec:
      containers:
      - name: myapp
        # CHANGE THIS line with your Docker Hub username
        image: jt3309/myapp:initial-green
        ports:
        - containerPort: 8080
        env:
          - name: APP_VERSION
            value: "v2.0 (Green Initial)" # Different version for green
          - name: DEPLOY_COLOR # Pass color to app
            value: "green"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name